### ISSUE TITLE
Could you provide the AF dataset or the checkpoint of the model?

### ISSUE THREAD

**Issue by blues-green** [Wiilly07/musical-stream-segregation#3]
Unfortunately, the following link of the AF dataset has failed.
https://www.reddit.com/r/datasets/comments/3akhxy/the_largest_midi_collection_on_the_internet/
https://mega.co.nz/#!Elg1TA7T!MXEZPzq9s9YObiUcMCoNQJmCbawZqzAkHzY4Ym6Gs_Q

**Comment by VickyChing** [comment]
Unfortunately, the following link of the AF dataset has failed.
[https://www.reddit.com/r/datasets/comments/3akhxy/the_largest_midi_collection_on_the_internet/](url)
[https://mega.co.nz/#!Elg1TA7T!MXEZPzq9s9YObiUcMCoNQJmCbawZqzAkHzY4Ym6Gs_Q](url)

**Comment by Wiilly07** [comment]
Here is the link to the dataset: [shorturl.at/hmouF](https://shorturl.at/hmouF)
The midi files I used for the paper are under the directory [AMERICAN_FOLK/1800s/].
